# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 11:45
from __future__ import unicode_literals

from django.db import migrations
import sitetools.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitetools', '0005_auto_20150317_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocumentversion',
            name='lang',
            field=sitetools.models.fields.LanguageField(choices=[(b'es', b'Spanish'), (b'en', b'English')], help_text='Legal document language for this version', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='sitelog',
            name='data',
            field=sitetools.models.fields.JSONField(blank=True, default=b'"\\"null\\""', help_text='Extra data for log message', null=True, verbose_name='Data'),
        ),
    ]
